--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gene/.config/wpg/wallpapers/wallpaper.png"

-- Special
background="#071013"
foreground="#c4ced1"
cursor="#c4ced1"

-- Colors
color0="#071013"
color1="#305B66"
color2="#4B5E65"
color3="#546970"
color4="#657C83"
color5="#428C98"
color6="#728A91"
color7="#c4ced1"
color8="#899092"
color9="#305B66"
color10="#4B5E65"
color11="#546970"
color12="#657C83"
color13="#428C98"
color14="#728A91"
color15="#c4ced1"
