# Shell variables
# Generated by 'wal'
wallpaper='/home/gene/.config/wpg/wallpapers/wallpaper.png'

# Special
background='#071013'
foreground='#c4ced1'
cursor='#c4ced1'

# Colors
color0='#071013'
color1='#305B66'
color2='#4B5E65'
color3='#546970'
color4='#657C83'
color5='#428C98'
color6='#728A91'
color7='#c4ced1'
color8='#899092'
color9='#305B66'
color10='#4B5E65'
color11='#546970'
color12='#657C83'
color13='#428C98'
color14='#728A91'
color15='#c4ced1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
